### ISSUE TITLE
Failing CI due to breaking change in pytest

### ISSUE THREAD

**Issue by tallamjr** [alan-turing-institute/bluebird#79]
In recent builds from https://github.com/alan-turing-institute/dodo/pull/79 and https://github.com/alan-turing-institute/dodo/pull/78 a failure has occurred on Travis which prints: 
```
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/p36/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/envs/p36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 61, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/miniconda/envs/p36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 182, in _prepareconfig
    config = get_config()
  File "/home/travis/miniconda/envs/p36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 156, in get_config
    pluginmanager.import_plugin(spec)
  File "/home/travis/miniconda/envs/p36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 530, in import_plugin
    __import__(importspec)
  File "/home/travis/miniconda/envs/p36/lib/python3.6/site-packages/_pytest/tmpdir.py", line 25, in <module>
    class TempPathFactory(object):
  File "/home/travis/miniconda/envs/p36/lib/python3.6/site-packages/_pytest/tmpdir.py", line 35, in TempPathFactory
    lambda p: Path(os.path.abspath(six.text_type(p)))
TypeError: attrib() got an unexpected keyword argument 'convert'
```
It appears that `pytest` seems to have the package `attrs` as a dependency. 

REF: https://stackoverflow.com/questions/58189683/typeerror-attrib-got-an-unexpected-keyword-argument-convert

*NOTE* This is the same error that has been outlined in https://github.com/alan-turing-institute/dodo/issues/80

**Comment by rkm** [comment]
Looks like this is fixed now, and we've upgraded pytest to 5.x 😄
